### ISSUE TITLE
Present/review initial HCR outcomes (Sprint 1.3)

### ISSUE THREAD

**Issue by nalcvp** [US-EPA-CAMD/HCD#12]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1597431454910?wid=0-1597761873119) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> PI1 Program Board - EPA CAMD Business Suite - ECMPS and AMPD

**Comment by krdeaven** [comment]
High level initial insights presented internally 9/15, interviews continuing.

**Comment by nsameerun** [comment]
Archive issue because it is a duplicate to issue #34
