### ISSUE TITLE
Identify personas 

### ISSUE THREAD

**Issue by nalcvp** [US-EPA-CAMD/HCD#2]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=0-1597096727938) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD

**Comment by krdeaven** [comment]
In progress as we conduct interviews. Beginning to identify persona candidates as interviews progress.

**Comment by krdeaven** [comment]
Is the analyst role that Chris mentioned a separate persona? - from UX meeting 9/22

**Comment by nsameerun** [comment]
Personas for ECMPS and AMPD identified and shared at UX Weekly meeting on 10-14-20.
