### ISSUE TITLE
Identify user flows

### ISSUE THREAD

**Issue by nalcvp** [US-EPA-CAMD/HCD#3]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=0-1597096712689) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD

**Comment by nsameerun** [comment]
Moving to P-2 at earliest due to research priorities ahead of it.
