### ISSUE TITLE
Research MVP Needs for EASY-Out 

### ISSUE THREAD

**Issue by krdeaven** [US-EPA-CAMD/HCD#38]
What are top level needs to sunset AMPD - time bound business need.

**Comment by nsameerun** [comment]
Notes from PI Backlog Refinement:

Goal: Be able to download more data at once than we can do right now - stay away from technology-dependent and focus on business need

This is about large and custom data sets, not just pre-packaged

Need to figure out the right user community who will use this feature

Andrew question: Should we show someone what this could look like?

Discussion of filter criteria that allow the users to customize reports - could be a design exercise as well as research along with this

Ming and Michelle:
With respect to API data, what do you need? 
With respect to FACTS data, what do you need?

Mike and Michelle: What is the MVP for CAMD Suite. What are we working toward?

Michelle: What research do we need to prioritize and what research do we need to hold back on?
