### ISSUE TITLE
Conduct Interview on Prepackaged Data 

### ISSUE THREAD

**Issue by nalcvp** [US-EPA-CAMD/HCD#8]
> [Open in MURAL](https://app.mural.co/t/epacamdbusinesssuiteecmpsand9948/m/epacamdbusinesssuiteecmpsand9948/1596809443620?wid=0-1597335502946) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CAMD 3-PI Roadmap - EPA CAMD Business Suite - ECMPS and AMPD

**Comment by krdeaven** [comment]
Interviews have started, initial interviews include questions on pre-packaged data and will inform next research.
